const main=document.getElementById('content');
const products=window.products;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const descriptions={'nomad-angel':'An ornate, sculptural silhouette, seen through a steppe-inspired editorial story.','tomiris':'A structured silhouette with ornamental detailing and a distinctive metalwork finish.','wonder-woman':'Strong curved lines and a sculpted waist. Explore the different styling and colour treatments in the gallery.','agent-007':'A sharp, fitted silhouette with a front zip, photographed in a dramatic black-and-red campaign.','fringe-belt':'Long fringe brings movement to a defined waist. Explore the different lengths and styling shown here.'};
function card(p){const src=p.images.find(image=>!usedImages.has(image))||p.images[0];usedImages.add(src);return '<article class="catalogue-item"><a class="card" href="#product/'+p.slug+'"><figure><img loading="lazy" src="'+src+'" alt="'+esc(p.name)+' — BLACK HORSE"></figure><h3>'+esc(p.name)+'</h3><p>'+p.category+' · View piece</p></a>'+leatherOptions(p)+'</article>'}
let usedImages=new Set();
function cards(items){return '<div class="grid">'+items.map(card).join('')+'</div>'}
function render(resetScroll=true){renderChrome();const hash=location.hash.slice(1)||'home';const [route,slug]=hash.split('/');usedImages=new Set(route==='home'?['https://black-horse-atelier.danayabanana.chatgpt.site/assets/107.jpg','https://black-horse-atelier.danayabanana.chatgpt.site/assets/109.jpg','https://black-horse-atelier.danayabanana.chatgpt.site/assets/165.jpg']:route==='product'?(products.find(p=>p.slug===slug)?.images||[]):[]);document.title='BLACK HORSE — '+(route==='product'?(products.find(p=>p.slug===slug)?.name||'Catalogue'):'The catalogue');
if(route==='product'){const p=products.find(p=>p.slug===slug);if(!p){main.innerHTML='<section class="atelier"><h1>Piece not found</h1><a class="text-link" href="#collection">Return to catalogue</a></section>';main.innerHTML=localizeHTML(main.innerHTML);return}
main.innerHTML='<section class="product"><a class="back" href="#collection">← Catalogue</a><div class="product-layout"><div><div class="gallery" id="gallery">'+p.images.map((src,i)=>'<img '+(i?'loading="lazy"':'')+' src="'+src+'" alt="'+esc(p.name)+' — view '+(i+1)+'">').join('')+'</div><button class="gallery-toggle" aria-expanded="false" aria-controls="gallery">View all '+p.images.length+' photographs</button></div><div class="product-info"><p class="eyebrow">'+p.category+'</p><h1>'+esc(p.name)+'</h1><p class="description">'+(descriptions[p.slug]||'Explore the silhouette, details and styling of '+esc(p.name)+' in the BLACK HORSE collection.')+'</p>'+leatherOptions(p)+'<div class="pending"><p>Price and availability: awaiting confirmation.</p><p>Sizes, materials, colour options and production time will be confirmed before ordering opens.</p></div><a class="button" href="#atelier">Contact BLACK HORSE on Instagram ↗</a><p class="small-note">Mention '+esc(p.name)+' in your message. This preview does not accept orders or payments.</p></div></div></section><section class="related"><h2>Explore more</h2>'+cards(products.filter(x=>x!==p).slice(0,4))+'</section>';
main.querySelector('.gallery-toggle').onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',expanded);document.getElementById('gallery').classList.toggle('expanded',expanded);e.currentTarget.textContent=expanded?'Show fewer photographs':'View all '+p.images.length+' photographs';};
}else if(route==='collection'){const category=['Corsets','Basques','Belts'].find(c=>c.toLowerCase()===slug);const list=category?products.filter(p=>p.category===category):products;main.innerHTML='<section class="collection-head"><p class="eyebrow">BLACK HORSE / Catalogue</p><h1>'+ (category||'The catalogue')+'</h1><nav class="categories" aria-label="Product categories">'+['All','Corsets','Basques','Belts'].map(c=>'<a '+((c===category||c==='All'&&!category)?'aria-current="page"':'')+' href="#collection'+(c==='All'?'':'/'+c.toLowerCase())+'">'+c+'</a>').join('')+'</nav><p class="count">'+list.length+' pieces · Launch selection to be confirmed</p></section>'+cards(list);
}else if(route==='story'){main.innerHTML='<section class="story"><img src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/107.jpg" alt="Nomad Angel photographed with a horse in a steppe landscape"><div class="copy"><p class="eyebrow">The BLACK HORSE world</p><h1>Rooted in spirit.<br>Shaped for presence.</h1><p>Discover Dinara’s world of sculptural corsets, ornamental details and expressive silhouettes.</p><p>The collection moves between sharply defined shapes and a richly detailed, steppe-inspired visual language.</p><a class="text-link" href="#collection">Explore the catalogue ↗</a></div></section>';
}else if(route==='atelier'){main.innerHTML='<section class="atelier"><p class="eyebrow">BLACK HORSE / Atelier</p><h1>A conversation<br>about your piece.</h1><p>For questions about a design, its fit or possible variations, contact BLACK HORSE directly. Include the piece’s name and what you would like to know.</p><p>Available sizes, custom options, lead times and prices are still being confirmed for this catalogue.</p><a class="button" href="https://ig.me/m/blackhorse.kz" target="_self">Open Instagram chat ↗</a><a class="text-link" href="https://www.instagram.com/blackhorse.kz/" target="_self">Open @blackhorse.kz profile ↗</a><p class="small-note">If chat does not open, visit our profile and tap Message. Instagram may ask you to sign in.</p></section>';
}else{main.innerHTML='<section class="hero"><img src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/107.jpg" alt="Nomad Angel corset, styled with a horse in the steppe"><img src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/109.jpg" alt="Ornamental details of the Nomad Angel corset"><div class="hero-copy"><p class="eyebrow">BLACK HORSE · The catalogue</p><h1>An untamed<br>kind of elegance.</h1><a class="text-link" href="#collection">Explore the catalogue ↗</a></div></section><section><div class="intro"><div><p class="eyebrow">A first look</p><h2>Shape. Spirit. Presence.</h2></div><a class="text-link" href="#collection">View all 21 pieces ↗</a></div>'+cards(products.slice(0,8))+'</section><section class="editorial"><figure><img loading="lazy" src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/165.jpg" alt="Wonder Woman sculptural corset with an ornamental headpiece"></figure><div class="copy"><p class="eyebrow">Sculptural expression</p><h2>Not just worn.<br>Felt.</h2><p>Defined waists. Dramatic lines.<br>Details that deserve a second look.</p><a class="text-link" href="#product/wonder-woman">Discover Wonder Woman ↗</a></div></section>'; }
main.innerHTML=localizeHTML(main.innerHTML);
document.title=translateText(document.title);
bindLeatherOptions();
if(route==='product'){const p=products.find(p=>p.slug===slug);const button=main.querySelector('.gallery-toggle');if(p&&button)button.onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',expanded);document.getElementById('gallery').classList.toggle('expanded',expanded);e.currentTarget.textContent=translateText(expanded?'Show fewer photographs':'View all '+p.images.length+' photographs');};}
if(resetScroll)window.scrollTo(0,0);
}
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});render();
