const main=document.getElementById('content');
const products=window.products;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const descriptions={'nomad-angel':'An ornate, sculptural silhouette, seen through a steppe-inspired editorial story.','tomiris':'A structured silhouette with ornamental detailing and a distinctive metalwork finish.','wonder-woman':'Strong curved lines and a sculpted waist. Explore the different styling and colour treatments in the gallery.','agent-007':'A sharp, fitted silhouette with a front zip, photographed in a dramatic black-and-red campaign.','fringe-belt':'Long fringe brings movement to a defined waist. Explore the different lengths and styling shown here.'};
const curatedLines=[
 {slug:'essential',en:'ESSENTIAL',ru:'ОСНОВА',kk:'НЕГІЗ',cover:'https://black-horse-atelier.danayabanana.chatgpt.site/assets/8.jpg',imageName:'Gia',items:products.map(p=>p.slug)},
 {slug:'statement',en:'STATEMENT',ru:'ХАРАКТЕР',kk:'МІНЕЗ',cover:'https://black-horse-atelier.danayabanana.chatgpt.site/assets/30.jpg',imageName:'Agent 007',items:[]},
 {slug:'atelier',en:'ATELIER',ru:'АТЕЛЬЕ',kk:'АТЕЛЬЕ',cover:'https://black-horse-atelier.danayabanana.chatgpt.site/assets/137.jpg',imageName:'Tomiris',items:[]}
];
const lineName=line=>line[language]||line.en;
function lineTiles(){return '<div class="line-grid">'+curatedLines.map(line=>'<a class="line-tile" href="#line/'+line.slug+'"><img src="'+line.cover+'" alt="'+esc(line.imageName)+' — BLACK HORSE"><span>'+lineName(line)+'</span><small>'+localized('Explore','Смотреть','Қарау')+' '+arrow+'</small></a>').join('')+'</div>'}
const information=[
 {slug:'order',title:['How to order','Как заказать','Тапсырыс беру'],text:['Choose a piece and ask us about your preferred leather colour and size on Instagram. Confirm the details and price, pay in full through Kaspi, then your piece is made for you.','Выберите модель и обсудите цвет кожи и размер в Instagram. После согласования деталей и цены — полная оплата через Kaspi, затем изготовление вашего изделия.','Үлгіні таңдап, былғары түсі мен өлшемін Instagram арқылы келісіңіз. Мәліметтер мен баға расталған соң Kaspi арқылы толық төлем жасайсыз, содан кейін бұйымыңыз дайындалады.']},
 {slug:'sizes',title:['Size guide','Размеры','Өлшемдер'],text:['Corsets come in two adjustable size ranges: XS/S/M and S/M/L. Message us for help choosing your fit. Exact measurements for each range are being confirmed.','Корсеты представлены в двух регулируемых размерных диапазонах: XS/S/M и S/M/L. Напишите нам, чтобы подобрать посадку. Точные мерки для каждого диапазона уточняются.','Корсеттер екі реттелетін өлшем ауқымында ұсынылады: XS/S/M және S/M/L. Өзіңізге сай өлшемді таңдау үшін бізге жазыңыз. Әр ауқымның нақты өлшемдері нақтылануда.']},
 {slug:'leather',title:['Leather & colours','Кожа и цвета','Былғары және түстер'],text:['Pieces are made from natural leather. Photographed colour samples are coming soon. Confirm the available shades for your chosen design with us.','Изделия выполнены из натуральной кожи. Фотографии доступных оттенков скоро появятся. Цвета для выбранной модели уточняйте у нас.','Бұйымдар табиғи былғарыдан жасалады. Қолжетімді түстердің фотосуреттері жақында қосылады. Таңдаған үлгіңізге арналған түстерді бізден нақтылаңыз.']},
 {slug:'delivery',title:['Making & delivery','Сроки и доставка','Дайындау және жеткізу'],text:['Made-to-order pieces take 2–4 weeks, depending on the model. Ask about ready-to-ship availability. Within Kazakhstan: pickup or Kazpost; postage is paid separately. Confirm your timeline and pickup location when ordering.','Изготовление под заказ занимает 2–4 недели в зависимости от модели. Наличие готовых изделий уточняйте. По Казахстану — самовывоз или Казпочта; доставка оплачивается отдельно. Точный срок и место самовывоза согласовываются при заказе.','Тапсырыспен дайындау үлгіге қарай 2–4 аптаға созылады. Дайын бұйымдардың бар-жоғын сұраңыз. Қазақстан бойынша алып кету немесе Қазпошта арқылы жеткізу бар; жеткізу ақысы бөлек төленеді. Нақты мерзім мен алып кету орнын тапсырыс кезінде келісіңіз.']},
 {slug:'care',title:['Leather care','Уход за кожей','Былғары күтімі'],text:['Care instructions for each finish will be added here. Ask us for guidance for your piece.','Здесь появятся рекомендации по уходу за разными видами отделки. Пока уточните уход за вашим изделием у нас.','Әр өңдеу түріне арналған күтім нұсқаулары осында қосылады. Әзірге бұйымыңыздың күтімі туралы бізден сұраңыз.']}
];
function infoButtons(){return '<nav class="info-buttons" aria-label="'+localized('Useful information','Полезная информация','Пайдалы ақпарат')+'">'+information.map(i=>'<a href="#info/'+i.slug+'">'+localized(...i.title)+'</a>').join('')+'</nav>'}
function shortHome(){return '<section class="home-portals" aria-label="BLACK HORSE"><a class="about-tile" href="#story"><img src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/165.jpg" alt="Wonder Woman — BLACK HORSE"><div><p>'+localized('the luxury of being yourself','роскошь быть собой','өзің болудың сән-салтанаты')+'</p><h1>'+localized('About us','О нас','Біз туралы')+' '+arrow+'</h1></div></a>'+lineTiles()+'</section>'+infoButtons()}
function card(p){const src=p.images.find(image=>!usedImages.has(image))||p.images[0];usedImages.add(src);return '<article class="catalogue-item"><a class="card" href="#product/'+p.slug+'"><figure><img loading="lazy" src="'+src+'" alt="'+esc(p.name)+' — BLACK HORSE"></figure><h3>'+esc(p.name)+'</h3><p>'+p.category+' · View piece</p></a>'+leatherOptions(p)+'</article>'}
let usedImages=new Set();
function cards(items){return '<div class="grid">'+items.map(card).join('')+'</div>'}
function render(resetScroll=true){renderChrome();const hash=location.hash.slice(1)||'home';const [route,slug]=hash.split('/');usedImages=new Set(route==='home'?['https://black-horse-atelier.danayabanana.chatgpt.site/assets/107.jpg','https://black-horse-atelier.danayabanana.chatgpt.site/assets/109.jpg','https://black-horse-atelier.danayabanana.chatgpt.site/assets/165.jpg',...curatedLines.map(line=>line.cover)]:route==='product'?(products.find(p=>p.slug===slug)?.images||[]):[]);document.title='BLACK HORSE — '+(route==='product'?(products.find(p=>p.slug===slug)?.name||'Catalogue'):'The catalogue');
if(route==='product'){const p=products.find(p=>p.slug===slug);if(!p){main.innerHTML='<section class="atelier"><h1>Piece not found</h1><a class="text-link" href="#collection">Return to catalogue</a></section>';main.innerHTML=localizeHTML(main.innerHTML);return}
main.innerHTML='<section class="product"><a class="back" href="#collection">← Catalogue</a><div class="product-layout"><div><div class="gallery" id="gallery">'+p.images.map((src,i)=>'<img '+(i?'loading="lazy"':'')+' src="'+src+'" alt="'+esc(p.name)+' — view '+(i+1)+'">').join('')+'</div><button class="gallery-toggle" aria-expanded="false" aria-controls="gallery">View all '+p.images.length+' photographs</button></div><div class="product-info"><p class="eyebrow">'+p.category+'</p><h1>'+esc(p.name)+'</h1><p class="description">'+(descriptions[p.slug]||'Explore the silhouette, details and styling of '+esc(p.name)+' in the BLACK HORSE collection.')+'</p>'+leatherOptions(p)+'<div class="pending"><p>Price and availability: awaiting confirmation.</p><p>Sizes, materials, colour options and production time will be confirmed before ordering opens.</p></div><a class="button" href="#atelier">Contact BLACK HORSE on Instagram ↗</a><p class="small-note">Mention '+esc(p.name)+' in your message. This preview does not accept orders or payments.</p></div></div></section><section class="related"><h2>Explore more</h2>'+cards(products.filter(x=>x!==p).slice(0,4))+'</section>';
main.querySelector('.gallery-toggle').onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',expanded);document.getElementById('gallery').classList.toggle('expanded',expanded);e.currentTarget.textContent=expanded?'Show fewer photographs':'View all '+p.images.length+' photographs';};
}else if(route==='line'){const line=curatedLines.find(item=>item.slug===slug);if(!line){location.hash='#collection';return}const list=line.items.map(item=>products.find(p=>p.slug===item)).filter(Boolean);main.innerHTML='<section class="collection-head"><a class="back" href="#home">← '+localized('Home','Главная','Басты бет')+'</a><p class="eyebrow">BLACK HORSE / '+localized('Catalogue','Каталог','Каталог')+'</p><h1>'+lineName(line)+'</h1><nav class="categories" aria-label="'+localized('Lines','Линии','Желілер')+'"><a href="#collection">'+localized('All pieces','Весь каталог','Барлық үлгілер')+'</a>'+curatedLines.map(item=>'<a '+(item===line?'aria-current="page"':'')+' href="#line/'+item.slug+'">'+lineName(item)+'</a>').join('')+'</nav><p class="count">'+list.length+' '+localized('pieces','моделей','үлгі')+'</p></section>'+(list.length?cards(list):'<section class="empty-line"><h2>'+localized('A new story is taking shape.','Новая история обретает форму.','Жаңа хикая қалыптасып келеді.')+'</h2><p>'+localized('Discover the current pieces in Essential.','Пока познакомьтесь с моделями в разделе «Основа».','Әзірге «Негіз» бөліміндегі үлгілерді қараңыз.')+'</p><a class="text-link" href="#line/essential">'+lineName(curatedLines[0])+' '+arrow+'</a></section>');
}else if(route==='collection'){const category=['Corsets','Basques','Belts'].find(c=>c.toLowerCase()===slug);const list=category?products.filter(p=>p.category===category):products;main.innerHTML='<section class="collection-head"><p class="eyebrow">BLACK HORSE / Catalogue</p><h1>'+ (category||'The catalogue')+'</h1><nav class="categories" aria-label="Product categories">'+['All','Corsets','Basques','Belts'].map(c=>'<a '+((c===category||c==='All'&&!category)?'aria-current="page"':'')+' href="#collection'+(c==='All'?'':'/'+c.toLowerCase())+'">'+c+'</a>').join('')+'</nav><p class="count">'+list.length+' pieces · Launch selection to be confirmed</p></section>'+cards(list);
}else if(route==='story'){main.innerHTML='<section class="story"><img src="https://black-horse-atelier.danayabanana.chatgpt.site/assets/107.jpg" alt="Nomad Angel photographed with a horse in a steppe landscape"><div class="copy"><p class="eyebrow">The BLACK HORSE world</p><h1>Rooted in spirit.<br>Shaped for presence.</h1><p>Discover Dinara’s world of sculptural corsets, ornamental details and expressive silhouettes.</p><p>The collection moves between sharply defined shapes and a richly detailed, steppe-inspired visual language.</p><a class="text-link" href="#collection">Explore the catalogue ↗</a></div></section>';
}else if(route==='atelier'){main.innerHTML='<section class="atelier"><p class="eyebrow">BLACK HORSE / Atelier</p><h1>A conversation<br>about your piece.</h1><p>For questions about a design, its fit or possible variations, contact BLACK HORSE directly. Include the piece’s name and what you would like to know.</p><p>Available sizes, custom options, lead times and prices are still being confirmed for this catalogue.</p><a class="button" href="https://ig.me/m/blackhorse.kz" target="_self">Open Instagram chat ↗</a><a class="text-link" href="https://www.instagram.com/blackhorse.kz/" target="_self">Open @blackhorse.kz profile ↗</a><p class="small-note">If chat does not open, visit our profile and tap Message. Instagram may ask you to sign in.</p></section>';
 }else if(route==='info'){const item=information.find(i=>i.slug===slug)||information[0];main.innerHTML='<section class="atelier information-page"><a class="back" href="#home">← '+localized('Home','Главная','Басты бет')+'</a><h1>'+localized(...item.title)+'</h1><p>'+localized(...item.text)+'</p><a class="text-link" href="#atelier">'+translateText('Message us')+' '+arrow+'</a></section>'+infoButtons();
}else{main.innerHTML=shortHome();}
document.body.classList.toggle('is-home',route==='home');

main.innerHTML=localizeHTML(main.innerHTML);
document.title=translateText(document.title);
bindLeatherOptions();
if(route==='product'){const p=products.find(p=>p.slug===slug);const button=main.querySelector('.gallery-toggle');if(p&&button)button.onclick=e=>{const expanded=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',expanded);document.getElementById('gallery').classList.toggle('expanded',expanded);e.currentTarget.textContent=translateText(expanded?'Show fewer photographs':'View all '+p.images.length+' photographs');};}
if(resetScroll)window.scrollTo(0,0);
}
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});render();

